/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) wamv_impl_dae_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sign CASADI_PREFIX(sign)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[4] = {0, 1, 0, 0};
static const casadi_int casadi_s4[23] = {10, 6, 0, 0, 0, 2, 6, 10, 14, 0, 1, 0, 1, 3, 4, 0, 1, 3, 4, 2, 3, 4, 5};
static const casadi_int casadi_s5[15] = {10, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s6[19] = {10, 4, 0, 3, 6, 9, 12, 3, 4, 5, 3, 4, 5, 3, 4, 5, 3, 4, 5};
static const casadi_int casadi_s7[11] = {10, 4, 0, 1, 2, 3, 4, 6, 7, 8, 9};

/* wamv_impl_dae_jac_x_xdot_u_z:(i0[6],i1[6],i2[4],i3[4],i4[],i5[0])->(o0[10x6,14nz],o1[10x6,6nz],o2[10x4,12nz],o3[10x4,4nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][3] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=sin(a1);
  a3=(a0*a2);
  a4=arg[0]? arg[0][4] : 0;
  a1=cos(a1);
  a5=(a4*a1);
  a3=(a3+a5);
  if (res[0]!=0) res[0][0]=a3;
  a3=(a0*a1);
  a5=(a4*a2);
  a3=(a3-a5);
  a3=(-a3);
  if (res[0]!=0) res[0][1]=a3;
  a1=(-a1);
  if (res[0]!=0) res[0][2]=a1;
  a3=(-a2);
  if (res[0]!=0) res[0][3]=a3;
  a3=5.5555555555555558e-03;
  a5=100.;
  a6=150.;
  a7=casadi_sign(a0);
  a7=(a6*a7);
  a7=(a0*a7);
  a8=casadi_fabs(a0);
  a6=(a6*a8);
  a7=(a7+a6);
  a7=(a5+a7);
  a7=(a3*a7);
  a7=(-a7);
  if (res[0]!=0) res[0][4]=a7;
  a7=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][5]=a7;
  if (res[0]!=0) res[0][6]=a2;
  if (res[0]!=0) res[0][7]=a1;
  a1=(-a7);
  if (res[0]!=0) res[0][8]=a1;
  a1=casadi_sign(a4);
  a1=(a5*a1);
  a1=(a4*a1);
  a2=casadi_fabs(a4);
  a2=(a5*a2);
  a1=(a1+a2);
  a5=(a5+a1);
  a5=(a3*a5);
  a5=(-a5);
  if (res[0]!=0) res[0][9]=a5;
  a5=-1.;
  if (res[0]!=0) res[0][10]=a5;
  a4=(-a4);
  if (res[0]!=0) res[0][11]=a4;
  if (res[0]!=0) res[0][12]=a0;
  a0=2.2421524663677130e-03;
  a4=800.;
  a5=casadi_sign(a7);
  a5=(a4*a5);
  a5=(a7*a5);
  a7=casadi_fabs(a7);
  a7=(a4*a7);
  a5=(a5+a7);
  a4=(a4+a5);
  a4=(a0*a4);
  a4=(-a4);
  if (res[0]!=0) res[0][13]=a4;
  a4=1.;
  if (res[1]!=0) res[1][0]=a4;
  if (res[1]!=0) res[1][1]=a4;
  if (res[1]!=0) res[1][2]=a4;
  if (res[1]!=0) res[1][3]=a4;
  if (res[1]!=0) res[1][4]=a4;
  if (res[1]!=0) res[1][5]=a4;
  a5=arg[2]? arg[2][2] : 0;
  a7=cos(a5);
  a1=(a3*a7);
  a1=(-a1);
  if (res[2]!=0) res[2][0]=a1;
  a5=sin(a5);
  a1=(a3*a5);
  a1=(-a1);
  if (res[2]!=0) res[2][1]=a1;
  a1=-2.3737759999999999e+00;
  a2=(a1*a7);
  a6=1.0271349999999999e+00;
  a8=(a6*a5);
  a2=(a2-a8);
  a2=(a0*a2);
  a2=(-a2);
  if (res[2]!=0) res[2][2]=a2;
  a2=arg[2]? arg[2][3] : 0;
  a8=cos(a2);
  a9=(a3*a8);
  a9=(-a9);
  if (res[2]!=0) res[2][3]=a9;
  a2=sin(a2);
  a9=(a3*a2);
  a9=(-a9);
  if (res[2]!=0) res[2][4]=a9;
  a9=(a6*a2);
  a10=2.3737759999999999e+00;
  a11=(a10*a8);
  a9=(a9-a11);
  a9=(a0*a9);
  a9=(-a9);
  if (res[2]!=0) res[2][5]=a9;
  a9=arg[2]? arg[2][0] : 0;
  a11=(a9*a5);
  a11=(a3*a11);
  if (res[2]!=0) res[2][6]=a11;
  a11=(a9*a7);
  a11=(a3*a11);
  a11=(-a11);
  if (res[2]!=0) res[2][7]=a11;
  a1=(a1*a9);
  a1=(a1*a5);
  a9=(a6*a9);
  a9=(a9*a7);
  a1=(a1+a9);
  a1=(a0*a1);
  if (res[2]!=0) res[2][8]=a1;
  a1=arg[2]? arg[2][1] : 0;
  a9=(a1*a2);
  a9=(a3*a9);
  if (res[2]!=0) res[2][9]=a9;
  a9=(a1*a8);
  a3=(a3*a9);
  a3=(-a3);
  if (res[2]!=0) res[2][10]=a3;
  a10=(a10*a1);
  a10=(a10*a2);
  a6=(a6*a1);
  a6=(a6*a8);
  a10=(a10+a6);
  a0=(a0*a10);
  a0=(-a0);
  if (res[2]!=0) res[2][11]=a0;
  if (res[3]!=0) res[3][0]=a4;
  if (res[3]!=0) res[3][1]=a4;
  if (res[3]!=0) res[3][2]=a4;
  if (res[3]!=0) res[3][3]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int wamv_impl_dae_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int wamv_impl_dae_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int wamv_impl_dae_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wamv_impl_dae_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int wamv_impl_dae_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wamv_impl_dae_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void wamv_impl_dae_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void wamv_impl_dae_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int wamv_impl_dae_jac_x_xdot_u_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int wamv_impl_dae_jac_x_xdot_u_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real wamv_impl_dae_jac_x_xdot_u_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wamv_impl_dae_jac_x_xdot_u_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wamv_impl_dae_jac_x_xdot_u_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wamv_impl_dae_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s2;
    case 5: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wamv_impl_dae_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int wamv_impl_dae_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int wamv_impl_dae_jac_x_xdot_u_z_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
