/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) wamv_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sign CASADI_PREFIX(sign)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};

/* wamv_expl_vde_adj:(i0[6],i1[6],i2[4],i3[])->(o0[10]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][2] : 0;
  a1=cos(a0);
  a2=arg[0]? arg[0][3] : 0;
  a3=arg[1]? arg[1][1] : 0;
  a4=(a2*a3);
  a4=(a1*a4);
  a0=sin(a0);
  a5=arg[0]? arg[0][4] : 0;
  a6=(a5*a3);
  a6=(a0*a6);
  a4=(a4-a6);
  a6=arg[1]? arg[1][0] : 0;
  a7=(a5*a6);
  a7=(a1*a7);
  a4=(a4-a7);
  a7=(a2*a6);
  a7=(a0*a7);
  a4=(a4-a7);
  if (res[0]!=0) res[0][2]=a4;
  a4=casadi_sign(a2);
  a7=7.2140000000000001e+01;
  a8=3.9969623086454293e-03;
  a9=arg[1]? arg[1][3] : 0;
  a9=(a8*a9);
  a7=(a7*a9);
  a4=(a4*a7);
  a7=-8.7916766000000002e-01;
  a10=arg[0]? arg[0][5] : 0;
  a11=(a7*a10);
  a12=2.0010005002501249e-03;
  a13=arg[1]? arg[1][5] : 0;
  a12=(a12*a13);
  a13=(a11*a12);
  a14=2.5019000000000000e+02;
  a15=arg[1]? arg[1][4] : 0;
  a8=(a8*a15);
  a15=(a10*a8);
  a16=(a14*a15);
  a13=(a13+a16);
  a4=(a4-a13);
  a13=(a0*a3);
  a4=(a4+a13);
  a13=(a1*a6);
  a4=(a4+a13);
  if (res[0]!=0) res[0][3]=a4;
  a4=(a10*a9);
  a13=(a14*a4);
  a16=-2.4143335000000002e-01;
  a10=(a16*a10);
  a17=(a10*a12);
  a13=(a13-a17);
  a1=(a1*a3);
  a13=(a13+a1);
  a0=(a0*a6);
  a13=(a13-a0);
  if (res[0]!=0) res[0][4]=a13;
  a10=(a10*a8);
  a13=(a5*a12);
  a13=(a16*a13);
  a0=(a2*a12);
  a0=(a7*a0);
  a13=(a13+a0);
  a10=(a10-a13);
  a16=(a16*a15);
  a10=(a10+a16);
  a2=(a14*a2);
  a2=(a2*a8);
  a10=(a10-a2);
  a11=(a11*a9);
  a10=(a10+a11);
  a7=(a7*a4);
  a10=(a10+a7);
  a14=(a14*a5);
  a14=(a14*a9);
  a10=(a10+a14);
  a14=arg[1]? arg[1][2] : 0;
  a10=(a10+a14);
  if (res[0]!=0) res[0][5]=a10;
  a10=-2.3737759999999999e+00;
  a14=arg[2]? arg[2][2] : 0;
  a5=cos(a14);
  a7=(a5*a12);
  a7=(a10*a7);
  a4=1.0271349999999999e+00;
  a14=sin(a14);
  a11=(a14*a12);
  a11=(a4*a11);
  a7=(a7-a11);
  a11=(a14*a8);
  a7=(a7+a11);
  a11=(a5*a9);
  a7=(a7+a11);
  if (res[0]!=0) res[0][6]=a7;
  a7=arg[2]? arg[2][3] : 0;
  a11=sin(a7);
  a2=(a11*a12);
  a2=(a4*a2);
  a16=2.3737759999999999e+00;
  a7=cos(a7);
  a15=(a7*a12);
  a15=(a16*a15);
  a2=(a2-a15);
  a15=(a11*a8);
  a2=(a2+a15);
  a15=(a7*a9);
  a2=(a2+a15);
  if (res[0]!=0) res[0][7]=a2;
  a2=arg[2]? arg[2][0] : 0;
  a15=(a2*a8);
  a15=(a5*a15);
  a13=(a4*a2);
  a13=(a13*a12);
  a5=(a5*a13);
  a10=(a10*a2);
  a10=(a10*a12);
  a10=(a14*a10);
  a5=(a5+a10);
  a15=(a15-a5);
  a2=(a2*a9);
  a14=(a14*a2);
  a15=(a15-a14);
  if (res[0]!=0) res[0][8]=a15;
  a15=arg[2]? arg[2][1] : 0;
  a4=(a4*a15);
  a4=(a4*a12);
  a4=(a7*a4);
  a16=(a16*a15);
  a16=(a16*a12);
  a16=(a11*a16);
  a4=(a4+a16);
  a8=(a15*a8);
  a7=(a7*a8);
  a4=(a4+a7);
  a15=(a15*a9);
  a11=(a11*a15);
  a4=(a4-a11);
  if (res[0]!=0) res[0][9]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int wamv_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int wamv_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int wamv_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wamv_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int wamv_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wamv_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void wamv_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void wamv_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int wamv_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int wamv_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real wamv_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wamv_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wamv_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wamv_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wamv_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int wamv_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int wamv_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
