<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>vrx_control</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="yang@todo.todo">yang</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <depend>vrx_gz</depend>
  <depend>vrx_ros</depend>
  <depend>vrx_urdf</depend>
  <depend>rclcpp</depend>  <!-- ROS 2 core library for C++ -->
  <depend>geometry_msgs</depend>  <!-- To send geometry messages (e.g., Twist) -->
  <depend>std_msgs</depend>  <!-- For standard messages -->
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>gazebo_msgs</depend>
  <depend>rclpy</depend>
  <depend>rcl_interfaces</depend>


  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
